### ISSUE TITLE
Creating docker file

### ISSUE THREAD

**Issue by chauhanprakhar** [CodeTrophs/Frontend#290]
Project setup can be messy and a participant can face many errors, creating a docker file can make it easy for project setup. So I want to create a docker file for this project.

**Comment by msk4862** [comment]
@chauhanprakhar what's the progress?

**Comment by Siddhant-K-code** [comment]
I can try this.

**Comment by Siddhant-K-code** [comment]
I am contributing under GSSOC but, still I think it is difficult and should be tagged as `Level 3`

**Comment by aryasoni98** [comment]
@Siddhant-K-code Go Head

**Comment by msk4862** [comment]
@Siddhant-K-code what's the progress?

**Comment by Siddhant-K-code** [comment]
Will create a PR, ASAP

**Comment by sonukushwaha403** [comment]
Can you please assign it to me, I can create docker file

**Comment by Siddhant-K-code** [comment]
should i put `report.20200509.210425.6764.0.001.json` in `.dockerignore` also, it's not needed. I guess!

**Comment by Siddhant-K-code** [comment]
getting this error, while building dockerfile :

```sh
=> ERROR [5/6] RUN npm install                                                          45.0s 
------
 > [5/6] RUN npm install:
#9 44.10 npm notice
#9 44.10 npm notice New minor version of npm available! 7.7.6 -> 7.10.0
#9 44.10 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v7.10.0>
#9 44.10 npm notice Run `npm install -g npm@7.10.0` to update!
#9 44.10 npm notice
#9 44.11 npm ERR! code 1
#9 44.11 npm ERR! path /app/node_modules/node-sass
#9 44.11 npm ERR! command failed
#9 44.11 npm ERR! command sh -c node scripts/build.js
#9 44.11 npm ERR! Building: /usr/local/bin/node /app/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
#9 44.11 npm ERR! gyp info it worked if it ends with ok
#9 44.11 npm ERR! gyp verb cli [
#9 44.11 npm ERR! gyp verb cli   '/usr/local/bin/node',
#9 44.11 npm ERR! gyp verb cli   '/app/node_modules/node-gyp/bin/node-gyp.js',
#9 44.11 npm ERR! gyp verb cli   'rebuild',
#9 44.11 npm ERR! gyp verb cli   '--verbose',
#9 44.12 npm ERR! gyp verb cli   '--libsass_ext=',
#9 44.12 npm ERR! gyp verb cli   '--libsass_cflags=',
#9 44.12 npm ERR! gyp verb cli   '--libsass_ldflags=',
#9 44.12 npm ERR! gyp verb cli   '--libsass_library='
#9 44.12 npm ERR! gyp verb cli ]
#9 44.12 npm ERR! gyp info using node-gyp@3.8.0
#9 44.12 npm ERR! gyp info using node@15.14.0 | linux | x64
#9 44.12 npm ERR! gyp verb command rebuild []
#9 44.12 npm ERR! gyp verb command clean []
#9 44.12 npm ERR! gyp verb clean removing "build" directory
#9 44.12 npm ERR! gyp verb command configure []
#9 44.12 npm ERR! gyp verb check python checking for Python executable "python2" in the PATH   
#9 44.12 npm ERR! gyp verb `which` failed Error: not found: python2
#9 44.12 npm ERR! gyp verb `which` failed     at getNotFoundError (/app/node_modules/which/which.js:13:12)
#9 44.12 npm ERR! gyp verb `which` failed     at F (/app/node_modules/which/which.js:68:19)    
#9 44.12 npm ERR! gyp verb `which` failed     at E (/app/node_modules/which/which.js:80:29)    
#9 44.12 npm ERR! gyp verb `which` failed     at /app/node_modules/which/which.js:89:16        
#9 44.12 npm ERR! gyp verb `which` failed     at /app/node_modules/isexe/index.js:42:5
#9 44.12 npm ERR! gyp verb `which` failed     at /app/node_modules/isexe/mode.js:8:5
#9 44.12 npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:193:21)     
#9 44.12 npm ERR! gyp verb `which` failed  python2 Error: not found: python2
#9 44.12 npm ERR! gyp verb `which` failed     at getNotFoundError (/app/node_modules/which/which.js:13:12)
#9 44.12 npm ERR! gyp verb `which` failed     at F (/app/node_modules/which/which.js:68:19)    
#9 44.12 npm ERR! gyp verb `which` failed     at E (/app/node_modules/which/which.js:80:29)    
#9 44.12 npm ERR! gyp verb `which` failed     at /app/node_modules/which/which.js:89:16        
#9 44.12 npm ERR! gyp verb `which` failed     at /app/node_modules/isexe/index.js:42:5
#9 44.12 npm ERR! gyp verb `which` failed     at /app/node_modules/isexe/mode.js:8:5
#9 44.12 npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:193:21) {   
#9 44.12 npm ERR! gyp verb `which` failed   code: 'ENOENT'
#9 44.12 npm ERR! gyp verb `which` failed }
#9 44.12 npm ERR! gyp verb check python checking for Python executable "python" in the PATH    
#9 44.12 npm ERR! gyp verb `which` failed Error: not found: python
#9 44.12 npm ERR! gyp verb `which` failed     at getNotFoundError (/app/node_modules/which/which.js:13:12)
#9 44.12 npm ERR! gyp verb `which` failed     at F (/app/node_modules/which/which.js:68:19)    
#9 44.13 npm ERR! gyp verb `which` failed     at E (/app/node_modules/which/which.js:80:29)    
#9 44.13 npm ERR! gyp verb `which` failed     at /app/node_modules/which/which.js:89:16        
#9 44.13 npm ERR! gyp verb `which` failed     at /app/node_modules/isexe/index.js:42:5
#9 44.13 npm ERR! gyp verb `which` failed     at /app/node_modules/isexe/mode.js:8:5
#9 44.13 npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:193:21)     
#9 44.13 npm ERR! gyp verb `which` failed  python Error: not found: python
#9 44.13 npm ERR! gyp verb `which` failed     at getNotFoundError (/app/node_modules/which/which.js:13:12)
#9 44.13 npm ERR! gyp verb `which` failed     at F (/app/node_modules/which/which.js:68:19)    
#9 44.13 npm ERR! gyp verb `which` failed     at E (/app/node_modules/which/which.js:80:29)    
#9 44.13 npm ERR! gyp verb `which` failed     at /app/node_modules/which/which.js:89:16        
#9 44.13 npm ERR! gyp verb `which` failed     at /app/node_modules/isexe/index.js:42:5
#9 44.13 npm ERR! gyp verb `which` failed     at /app/node_modules/isexe/mode.js:8:5
#9 44.13 npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:193:21) {   
#9 44.13 npm ERR! gyp verb `which` failed   code: 'ENOENT'
#9 44.13 npm ERR! gyp verb `which` failed }
#9 44.13 npm ERR! gyp ERR! configure error
#9 44.13 npm ERR! gyp ERR! stack Error: Can't find Python executable "python", you can set the 
PYTHON env variable.
#9 44.13 npm ERR! gyp ERR! stack     at PythonFinder.failNoPython (/app/node_modules/node-gyp/lib/configure.js:484:19)
#9 44.13 npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/app/node_modules/node-gyp/lib/configure.js:406:16)
#9 44.13 npm ERR! gyp ERR! stack     at F (/app/node_modules/which/which.js:68:16)
#9 44.13 npm ERR! gyp ERR! stack     at E (/app/node_modules/which/which.js:80:29)
#9 44.13 npm ERR! gyp ERR! stack     at /app/node_modules/which/which.js:89:16
#9 44.13 npm ERR! gyp ERR! stack     at /app/node_modules/isexe/index.js:42:5
#9 44.14 npm ERR! gyp ERR! stack     at /app/node_modules/isexe/mode.js:8:5
#9 44.14 npm ERR! gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:193:21)
#9 44.14 npm ERR! gyp ERR! System Linux 4.19.128-microsoft-standard
#9 44.14 npm ERR! gyp ERR! command "/usr/local/bin/node" "/app/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
#9 44.14 npm ERR! gyp ERR! cwd /app/node_modules/node-sass
#9 44.14 npm ERR! gyp ERR! node -v v15.14.0
#9 44.14 npm ERR! gyp ERR! node-gyp -v v3.8.0
#9 44.14 npm ERR! gyp ERR! not ok
#9 44.14 npm ERR! Build failed with error code: 1
#9 44.42
#9 44.42 npm ERR! A complete log of this run can be found in:
#9 44.42 npm ERR!     /root/.npm/_logs/2021-04-20T03_28_10_238Z-debug.log
------
executor failed running [/bin/sh -c npm install]: exit code: 1
```

**Comment by Siddhant-K-code** [comment]
this can be issue :

```sh
Your project has both `sass` and `node-sass` installed as dependencies, but should only use one or the other. Please remove the `node-sass` dependency from your project.
```

**Comment by Siddhant-K-code** [comment]
File Created and running perfectly fine. 

soon will change the docs accr. to it.

**Comment by Siddhant-K-code** [comment]
@aryasoni98 or any more collaborators, can you give your docker id, so i can add you as a collaborator for docker image.

**Comment by aryasoni98** [comment]
> @aryasoni98 or any other collaborator, can you give your docker id, so i can add you as a collaborator for docker image.

@Siddhant-K-code  Docker ID : `a1s1cmd01`

**Comment by Siddhant-K-code** [comment]
> Docker ID : `a1s1cmd01`

[This](https://hub.docker.com/u/a1s1cmd01) Collaborator has been added

**Comment by subhangi2731** [comment]
@aryasoni98 please assign me this issue

**Comment by aryasoni98** [comment]
@subhangi2731  Sure

**Comment by Siddhant-K-code** [comment]
@aryasoni98 IDK what you guys are doing the PR was open for so long but no response :(

**Comment by aryasoni98** [comment]
@Siddhant-K-code  bcz I don't know about docker and how it's work. Currently I'm learning stage.  Just reopen the PR and one of GSSoC mentors review asap . . .First priority @msk4862 @pinkman7009 @Anurag5086
